### ISSUE TITLE
Proposal For Copy Writing

### ISSUE THREAD

**Issue by ewuoso** [cryptohazard/hackico#1]
I just checked your project and i feel it is missing out some important details like faq, about us, contact us, privacy policy etc. If i you dont mind i am available and i can write it for you.

ewuosoolusesi@gmail.com

**Comment by cryptohazard** [comment]
Thanks for the suggestion. Maybe if I had publish this project earlier it would have been interesting to add that much details but the EOS ICO is closing soon.

**Comment by ewuoso** [comment]
So what are you saying now?

**Comment by cryptohazard** [comment]
I am just saying that this project doesn't need copy writing. 
Except if there is another ICO following the same model as EOS, this project won't be useful after the EOS ICO ends. So I don't think there is any point in writing details like faq...

Thanks for the offer though.

**Comment by ewuoso** [comment]
Thanks
