### ISSUE TITLE
Logo proposal for Hackico

### ISSUE THREAD

**Issue by radudangratian** [cryptohazard/hackico#2]
Hello! After we talked on Discord, here it;s my final proposal for you.Regards!

![hackico](https://user-images.githubusercontent.com/34451833/39637092-b471864a-4fca-11e8-9460-95354d53096e.png)

[Gdrive](https://drive.google.com/open?id=1Lhd3JdTv6xisoSme_upHEiYnZp_oBco6)

**Comment by cryptohazard** [comment]
Cool. I am adding it to the readme now ;-). 
Good job!
